### ISSUE TITLE
升级0.18.2有问题

### ISSUE THREAD

**Issue by ushtar** [houzi-/Koolshare-Clash-hack#2]
![2](https://user-images.githubusercontent.com/70705232/194449907-01cf7bff-3cc8-4bb5-8f1a-f056459e248e.gif)
所有版本2.36以上都是这个问题

**Comment by houzi-** [comment]
是否卸载了再重新安装呢

**Comment by ushtar** [comment]
> 是否卸载了再重新安装呢

没有虚拟机重置系统之后才安装的

**Comment by houzi-** [comment]
你测试一下安装其它插件是否正常
